# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

###TO-DO###
# func to refresh chat logs
# func to refresh friends list
# func to be activated when pressed a button that adds the message box contents to a list and then clears the message box
# func to refresh the chats list

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self):
        # define general use vars
        # sets the scale factor (default is 3)
        self.ScaleFactor = 3
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(562*self.ScaleFactor, 343*self.ScaleFactor)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ChatList = QtWidgets.QListView(self.centralwidget)
        self.ChatList.setGeometry(QtCore.QRect(-5*self.ScaleFactor, 10*self.ScaleFactor, 376*self.ScaleFactor, 256*self.ScaleFactor))
        self.ChatList.setObjectName("ChatList")
        self.HeaderLabel = QtWidgets.QLabel(self.centralwidget)
        self.HeaderLabel.setGeometry(QtCore.QRect(0, 0, 150*self.ScaleFactor, 11*self.ScaleFactor))
        self.HeaderLabel.setObjectName("HeaderLabel")
        self.ChatsList = QtWidgets.QListView(self.centralwidget)
        self.ChatsList.setGeometry(QtCore.QRect(370*self.ScaleFactor, 10*self.ScaleFactor, 106*self.ScaleFactor, 291*self.ScaleFactor))
        self.ChatsList.setObjectName("ChatsList")
        self.FreindsList = QtWidgets.QListView(self.centralwidget)
        self.FreindsList.setGeometry(QtCore.QRect(475*self.ScaleFactor, 10*self.ScaleFactor, 86*self.ScaleFactor, 291*self.ScaleFactor))
        self.FreindsList.setObjectName("FreindsList")
        self.SendButton = QtWidgets.QPushButton(self.centralwidget)
        self.SendButton.setGeometry(QtCore.QRect(341*self.ScaleFactor, 265*self.ScaleFactor, 31*self.ScaleFactor, 36*self.ScaleFactor))
        self.SendButton.setObjectName("SendButton")
        self.MessageArea = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.MessageArea.setGeometry(QtCore.QRect(0*self.ScaleFactor, 265*self.ScaleFactor, 341*self.ScaleFactor, 36*self.ScaleFactor))
        self.MessageArea.setObjectName("MessageArea")
        self.ActiveChatters = QtWidgets.QLabel(self.centralwidget)
        self.ActiveChatters.setGeometry(QtCore.QRect(160*self.ScaleFactor, 0, 95*self.ScaleFactor, 11*self.ScaleFactor))
        self.ActiveChatters.setObjectName("ActiveChatters")
        self.ActiveFriends = QtWidgets.QLabel(self.centralwidget)
        self.ActiveFriends.setGeometry(QtCore.QRect(265*self.ScaleFactor, 0, 85*self.ScaleFactor, 11*self.ScaleFactor))
        self.ActiveFriends.setObjectName("ActiveFriends")
        self.Chats = QtWidgets.QLabel(self.centralwidget)
        self.Chats.setGeometry(QtCore.QRect(370*self.ScaleFactor, 0, 39*self.ScaleFactor, 11*self.ScaleFactor))
        self.Chats.setObjectName("Chats")
        self.Friends = QtWidgets.QLabel(self.centralwidget)
        self.Friends.setGeometry(QtCore.QRect(480*self.ScaleFactor, 0, 39*self.ScaleFactor, 11*self.ScaleFactor))
        self.Friends.setObjectName("Friends")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 562*self.ScaleFactor, 20*self.ScaleFactor))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stellar Client"))
        self.HeaderLabel.setText(_translate("MainWindow", "Mon Day Year@Hour:Minute:Second"))
        self.SendButton.setText(_translate("MainWindow", "Send"))
        self.ActiveChatters.setText(_translate("MainWindow", "Active Chatters: 12/15"))
        self.ActiveFriends.setText(_translate("MainWindow", "Active Friends: 20/30"))
        self.Chats.setText(_translate("MainWindow", "Chats:"))
        self.Friends.setText(_translate("MainWindow", "Freinds:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
