# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

###TO-DO###
# func to refresh chat logs
# func to refresh friends list
# func to be activated when pressed a button that adds the message box contents to a list and then clears the message box
# func to refresh the chats list

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItemModel, QStandardItem
import keyboard
import time
import pyautogui
import threading
import string

class Ui_MainWindow(QtCore.QObject):
    def __init__(self, mainWindow):
        super().__init__()
        self.setupUi(mainWindow)
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.periodic)
        self.timer.start(500)
        self.messages = []
        self.latestMessage = ''
        self.chatModel = QtCore.QStringListModel()
        self.ChatMessages.setModel(self.chatModel)
        self.currentChatList = self.chatModel.stringList()
        self.appRunning = 1

    def setupUi(self, MainWindow):
        # sets the scale factor (default is 3)
        self.ScaleFactor = 5
    
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(562*self.ScaleFactor, 343*self.ScaleFactor)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ChatMessages = QtWidgets.QListView(self.centralwidget)
        self.ChatMessages.setGeometry(QtCore.QRect(-5*self.ScaleFactor, 10*self.ScaleFactor, 376*self.ScaleFactor, 256*self.ScaleFactor))
        self.ChatMessages.setObjectName("ChatList")
        self.HeaderLabel = QtWidgets.QLabel(self.centralwidget)
        self.HeaderLabel.setGeometry(QtCore.QRect(0, 0, 150*self.ScaleFactor, 11*self.ScaleFactor))
        
        self.HeaderLabel.setObjectName("HeaderLabel")
        self.ChatsList = QtWidgets.QListView(self.centralwidget)
        self.ChatsList.setGeometry(QtCore.QRect(370*self.ScaleFactor, 10*self.ScaleFactor, 106*self.ScaleFactor, 291*self.ScaleFactor))
        self.ChatsList.setObjectName("ChatsList")
        self.FreindsList = QtWidgets.QListView(self.centralwidget)
        self.FreindsList.setGeometry(QtCore.QRect(475*self.ScaleFactor, 10*self.ScaleFactor, 86*self.ScaleFactor, 291*self.ScaleFactor))
        self.FreindsList.setObjectName("FreindsList")
        self.SendButton = QtWidgets.QPushButton(self.centralwidget)
        self.SendButton.setGeometry(QtCore.QRect(341*self.ScaleFactor, 265*self.ScaleFactor, 31*self.ScaleFactor, 36*self.ScaleFactor))
        self.SendButton.setObjectName("SendButton")
        self.MessageArea = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.MessageArea.setGeometry(QtCore.QRect(0*self.ScaleFactor, 265*self.ScaleFactor, 341*self.ScaleFactor, 36*self.ScaleFactor))
        self.MessageArea.setObjectName("MessageArea")
        self.ActiveChatters = QtWidgets.QLabel(self.centralwidget)
        self.ActiveChatters.setGeometry(QtCore.QRect(160*self.ScaleFactor, 0, 95*self.ScaleFactor, 11*self.ScaleFactor))
        self.ActiveChatters.setObjectName("ActiveChatters")
        self.ActiveFriends = QtWidgets.QLabel(self.centralwidget)
        self.ActiveFriends.setGeometry(QtCore.QRect(265*self.ScaleFactor, 0, 85*self.ScaleFactor, 11*self.ScaleFactor))
        self.ActiveFriends.setObjectName("ActiveFriends")
        self.Chats = QtWidgets.QLabel(self.centralwidget)
        self.Chats.setGeometry(QtCore.QRect(370*self.ScaleFactor, 0, 39*self.ScaleFactor, 11*self.ScaleFactor))
        self.Chats.setObjectName("Chats")
        self.Friends = QtWidgets.QLabel(self.centralwidget)
        self.Friends.setGeometry(QtCore.QRect(480*self.ScaleFactor, 0, 39*self.ScaleFactor, 11*self.ScaleFactor))
        self.Friends.setObjectName("Friends")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 562*self.ScaleFactor, 20*self.ScaleFactor))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "StellarClientUI"))
        self.HeaderLabel.setText(_translate("MainWindow", "Mon Day Year@Hour:Minute:Second"))
        self.SendButton.setText(_translate("MainWindow", "Send"))
        self.ActiveChatters.setText(_translate("MainWindow", "Active Chatters: 12/15"))
        self.ActiveFriends.setText(_translate("MainWindow", "Active Friends: 20/30"))
        self.Chats.setText(_translate("MainWindow", "Chats:"))
        self.Friends.setText(_translate("MainWindow", "Freinds:"))
    
    def eventFilter(self, obj, event):
        if obj == self.MessageArea and event.type() == QtCore.QEvent.KeyPress:
            if event.key() in (QtCore.Qt.Key_Return, QtCore.Qt.Key_Enter):
                if not (event.modifiers() & QtCore.Qt.ShiftModifier):
                    self.getMessageBox()
                    return True
        return super().eventFilter(obj, event)

    def getMessageBox(self):
        message = self.MessageArea.toPlainText()
        cont = False
        for i in message:
            if i in string.printable and i != ' ':
                cont = True
        if cont:
            self.MessageArea.setPlainText('')
            self.messages.append(message)
            self.latestMessage = message
            self.setChatBoxText(message)

    def feedMessageData(self):
        if keyboard.is_pressed('enter'):
            self.getMessageBox()
            time.sleep(0.01)
            pyautogui.press('backspace')

    def setChatBoxText(self, text: str):
        # # newText = self.ChatMessages.text() + '\n' + text
        # # self.ChatMessages.setText(newText)
        self.currentChatList.append(text)
        self.chatModel.setStringList(self.currentChatList)
        self.ChatMessages.scrollToBottom()
    
    def timeUpdate(self):
        # Get the current local time struct
        current_time_struct = time.localtime()

        # %m: Month as a zero-padded decimal number
        # %d: Day of the month as a zero-padded decimal number
        # %Y: Year with century as a decimal number
        # %H: Hour (24-hour clock) as a zero-padded decimal number
        # %M: Minute as a zero-padded decimal number
        # %S: Second as a zero-padded decimal number
        formatted_time = time.strftime("%m/%d/%Y, %H:%M:%S", current_time_struct)

        self.HeaderLabel.setText(formatted_time)

    def periodic(self):
        self.timeUpdate()

    def getMessageList(self):
        return self.messages
    
    def getLatestMessage(self):
        return self.latestMessage


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(MainWindow)
    # timeThread = threading.Thread(target=ui.timeUpdate)
    # timeThread.start()
    # messagesThread = threading.Thread(target=ui.feedMessageData)
    # messagesThread.start()
    MainWindow.show()
    app.exec_()

    ui.appRunning = 0
    print(ui.messages)
