# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItemModel, QStandardItem
import keyboard
import time
import pyautogui
import threading
import string

class Ui_MainWindow(QtCore.QObject):
    def __init__(self, mainWindow):
        super().__init__()
        self.setupUi(mainWindow)
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.periodic)
        self.timer.start(500)
        self.messages = []
        self.latestMessage = ''
        self.chatModel = QtCore.QStringListModel()
        self.ChatMessages.setModel(self.chatModel)
        self.currentChatList = self.chatModel.stringList()
        self.appRunning = 1

    def setupUi(self, MainWindow):
        self.ScaleFactor = 4
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(562*self.ScaleFactor, 331*self.ScaleFactor)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ChatMessages = QtWidgets.QListView(self.centralwidget)
        self.ChatMessages.setGeometry(QtCore.QRect(5*self.ScaleFactor, 10*self.ScaleFactor, 366*self.ScaleFactor, 256*self.ScaleFactor))
        self.ChatMessages.setObjectName("ChatList")
        self.HeaderLabel = QtWidgets.QLabel(self.centralwidget)
        self.HeaderLabel.setGeometry(QtCore.QRect(self.ScaleFactor, self.ScaleFactor, 150*self.ScaleFactor, 11*self.ScaleFactor))
        self.HeaderLabel.setObjectName("HeaderLabel")
        self.ChatScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.ChatScrollBar.setGeometry(QtCore.QRect(360*self.ScaleFactor, 10*self.ScaleFactor, 10*self.ScaleFactor, 251*self.ScaleFactor))
        self.ChatScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.ChatScrollBar.setObjectName("ChatScrollBar")
        self.ChatsList = QtWidgets.QListView(self.centralwidget)
        self.ChatsList.setGeometry(QtCore.QRect(370*self.ScaleFactor, 10*self.ScaleFactor, 101*self.ScaleFactor, 281*self.ScaleFactor))
        self.ChatsList.setObjectName("ChatsList")
        self.FreindsList = QtWidgets.QListView(self.centralwidget)
        self.FreindsList.setGeometry(QtCore.QRect(475*self.ScaleFactor, 10*self.ScaleFactor, 81*self.ScaleFactor, 281*self.ScaleFactor))
        self.FreindsList.setObjectName("FreindsList")
        self.ChatListScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.ChatListScrollBar.setGeometry(QtCore.QRect(470*self.ScaleFactor, 10*self.ScaleFactor, 5*self.ScaleFactor, 281*self.ScaleFactor))
        self.ChatListScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.ChatListScrollBar.setObjectName("ChatListScrollBar")
        self.verticalScrollBar_3 = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar_3.setGeometry(QtCore.QRect(555*self.ScaleFactor, 10*self.ScaleFactor, 5*self.ScaleFactor, 281*self.ScaleFactor))
        self.verticalScrollBar_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_3.setObjectName("verticalScrollBar_3")
        self.SendButton = QtWidgets.QPushButton(self.centralwidget)
        self.SendButton.setGeometry(QtCore.QRect(336*self.ScaleFactor, 265*self.ScaleFactor, 36*self.ScaleFactor, 26*self.ScaleFactor))
        self.SendButton.setObjectName("SendButton")
        self.MessageArea = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.MessageArea.setGeometry(QtCore.QRect(0*self.ScaleFactor, 265*self.ScaleFactor, 326*self.ScaleFactor, 26*self.ScaleFactor))
        self.MessageArea.setObjectName("MessageArea")
        self.MessageArea.installEventFilter(self)
        self.MessageScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.MessageScrollBar.setGeometry(QtCore.QRect(325*self.ScaleFactor, 265*self.ScaleFactor, 10*self.ScaleFactor, 26*self.ScaleFactor))
        self.MessageScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.MessageScrollBar.setObjectName("MessageScrollBar")
        self.ActiveChatters = QtWidgets.QLabel(self.centralwidget)
        self.ActiveChatters.setGeometry(QtCore.QRect(160*self.ScaleFactor, 0*self.ScaleFactor, 95*self.ScaleFactor, 11*self.ScaleFactor))
        self.ActiveChatters.setObjectName("ActiveChatters")
        self.ActiveFriends = QtWidgets.QLabel(self.centralwidget)
        self.ActiveFriends.setGeometry(QtCore.QRect(265*self.ScaleFactor, 0*self.ScaleFactor, 85*self.ScaleFactor, 11*self.ScaleFactor))
        self.ActiveFriends.setObjectName("ActiveFriends")
        self.Seperator1 = QtWidgets.QFrame(self.centralwidget)
        self.Seperator1.setGeometry(QtCore.QRect(357*self.ScaleFactor, 0*self.ScaleFactor, 16*self.ScaleFactor, 10*self.ScaleFactor))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Seperator1.setPalette(palette)
        self.Seperator1.setFrameShape(QtWidgets.QFrame.VLine)
        self.Seperator1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Seperator1.setObjectName("Seperator1")
        self.Seperator2 = QtWidgets.QFrame(self.centralwidget)
        self.Seperator2.setGeometry(QtCore.QRect(465*self.ScaleFactor, 0*self.ScaleFactor, 16*self.ScaleFactor, 10*self.ScaleFactor))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Seperator2.setPalette(palette)
        self.Seperator2.setFrameShape(QtWidgets.QFrame.VLine)
        self.Seperator2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Seperator2.setObjectName("Seperator2")
        self.Chats = QtWidgets.QLabel(self.centralwidget)
        self.Chats.setGeometry(QtCore.QRect(370*self.ScaleFactor, 0*self.ScaleFactor, 39*self.ScaleFactor, 11*self.ScaleFactor))
        self.Chats.setObjectName("Chats")
        self.Friends = QtWidgets.QLabel(self.centralwidget)
        self.Friends.setGeometry(QtCore.QRect(480*self.ScaleFactor, 0*self.ScaleFactor, 39*self.ScaleFactor, 11*self.ScaleFactor))
        self.Friends.setObjectName("Friends")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0*self.ScaleFactor, 0*self.ScaleFactor, 562*self.ScaleFactor, 20*self.ScaleFactor))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.HeaderLabel.setText(_translate("MainWindow", "Mon Day Year@Hour:Minute:Second"))
        self.SendButton.setText(_translate("MainWindow", "Send"))
        self.ActiveChatters.setText(_translate("MainWindow", "Active Chatters: 12/15"))
        self.ActiveFriends.setText(_translate("MainWindow", "Active Friends: 20/30"))
        self.Chats.setText(_translate("MainWindow", "Chats:"))
        self.Friends.setText(_translate("MainWindow", "Freinds:"))
    
    def eventFilter(self, obj, event):
        if obj == self.MessageArea and event.type() == QtCore.QEvent.KeyPress:
            if event.key() in (QtCore.Qt.Key_Return, QtCore.Qt.Key_Enter):
                if not (event.modifiers() & QtCore.Qt.ShiftModifier):
                    self.getMessageBox()
                    return True
        return super().eventFilter(obj, event)

    def getMessageBox(self):
        message = self.MessageArea.toPlainText()
        cont = False
        for i in message:
            if i in string.printable and i != ' ':
                cont = True
        if cont:
            self.MessageArea.setPlainText('')
            self.messages.append(message)
            self.latestMessage = message
            self.setChatBoxText(message)

    def feedMessageData(self):
        if keyboard.is_pressed('enter'):
            self.getMessageBox()
            time.sleep(0.01)
            pyautogui.press('backspace')

    def setChatBoxText(self, text: str):
        # # newText = self.ChatMessages.text() + '\n' + text
        # # self.ChatMessages.setText(newText)
        self.currentChatList.append(text)
        self.chatModel.setStringList(self.currentChatList)
        self.ChatMessages.scrollToBottom()
    
    def timeUpdate(self):
        # Get the current local time struct
        current_time_struct = time.localtime()

        # %m: Month as a zero-padded decimal number
        # %d: Day of the month as a zero-padded decimal number
        # %Y: Year with century as a decimal number
        # %H: Hour (24-hour clock) as a zero-padded decimal number
        # %M: Minute as a zero-padded decimal number
        # %S: Second as a zero-padded decimal number
        formatted_time = time.strftime("%m/%d/%Y, %H:%M:%S", current_time_struct)

        self.HeaderLabel.setText(formatted_time)

    def periodic(self):
        self.timeUpdate()

    def getMessageList(self):
        return self.messages
    
    def getLatestMessage(self):
        return self.latestMessage


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(MainWindow)
    # timeThread = threading.Thread(target=ui.timeUpdate)
    # timeThread.start()
    # messagesThread = threading.Thread(target=ui.feedMessageData)
    # messagesThread.start()
    MainWindow.show()
    app.exec_()

    ui.appRunning = 0
    print(ui.messages)
